### ISSUE TITLE
The status label at the bottom of the RoomsList is not always correct

### ISSUE THREAD

**Issue by aaravlu** [project-robius/robrix#188] opened 2024-10-11 09:36 UTC

**Comment by Demolemon11** [comment] 2024-10-11 09:40
#### Only at the first time.
#### They two status can be displayed normally when the dir (.local/share/robrix)  exists matrix caches.

**Comment by kevinaboos** [comment] 2024-10-11 23:50
sorry, can you clarify or provide a screenshot? I assume you're talking about the `status` label in the RoomsList?

**Comment by Demolemon11** [comment] 2024-10-12 02:16
No need to look at this, I have closed my pr, excuse me : ), I will close this issue later : )

**Comment by kevinaboos** [comment] 2024-10-12 20:54
I'm unable to reproduce this; feel free to re-open when you can demonstrate the problem.

**Comment by Demolemon11** [comment] 2024-10-13 01:21
> I'm unable to reproduce this; feel free to re-open when you can demonstrate the problem.

That's ok, please reopen this: )

**Comment by kevinaboos** [comment] 2024-11-07 20:12
Sorry I missed your comment! I'll re-open this.

**Comment by kevinaboos** [comment] 2024-11-07 20:13
Can you kindly provide different instructions on how to reproduce this? The presence of the app data directory does not seem to have any affect here.

Perhaps this is a Makepad problem on a particular platform? Which platform do you experience this on? I can't seem to repro it on macOS at least.

**Comment by kevinaboos** [comment] 2024-11-07 22:32
ok so i was able to reproduce this but not based on the conditions you shared above. Interesting!

So far it just seems to occur randomly, but it should be easy to diagnose.

<img width="391" alt="image" src="https://github.com/user-attachments/assets/ea742b30-3fd0-4380-b998-3833cba4a30c">

**Comment by Demolemon11** [comment] 2024-11-08 14:37
I am looking at this.

**Closed** 2024-12-17 00:22 UTC
Labels: bug, help wanted
